import '../models/deck_bucket.dart';

class StaplesDatabase {
  static const Map<String, DeckBucket> knownStaples = {
    // Ramp
    'sol ring': DeckBucket.ramp,
    'arcane signet': DeckBucket.ramp,
    'mana crypt': DeckBucket.ramp,
    'mana vault': DeckBucket.ramp,
    'mox diamond': DeckBucket.ramp,
    'chrome mox': DeckBucket.ramp,
    'mox opal': DeckBucket.ramp,
    'mox amber': DeckBucket.ramp,
    'lotus petal': DeckBucket.ramp,
    'fellwar stone': DeckBucket.ramp,
    'thought vessel': DeckBucket.ramp,
    'mind stone': DeckBucket.ramp,
    'everflowing chalice': DeckBucket.ramp,
    'prismatic lens': DeckBucket.ramp,
    'commanders sphere': DeckBucket.ramp,
    'chromatic lantern': DeckBucket.ramp,
    'talisman of progress': DeckBucket.ramp,
    'talisman of dominance': DeckBucket.ramp,
    'talisman of indulgence': DeckBucket.ramp,
    'talisman of impulse': DeckBucket.ramp,
    'talisman of unity': DeckBucket.ramp,
    'talisman of hierarchy': DeckBucket.ramp,
    'talisman of creativity': DeckBucket.ramp,
    'talisman of resilience': DeckBucket.ramp,
    'talisman of conviction': DeckBucket.ramp,
    'talisman of curiosity': DeckBucket.ramp,
    'azorius signet': DeckBucket.ramp,
    'dimir signet': DeckBucket.ramp,
    'rakdos signet': DeckBucket.ramp,
    'gruul signet': DeckBucket.ramp,
    'selesnya signet': DeckBucket.ramp,
    'orzhov signet': DeckBucket.ramp,
    'izzet signet': DeckBucket.ramp,
    'golgari signet': DeckBucket.ramp,
    'boros signet': DeckBucket.ramp,
    'simic signet': DeckBucket.ramp,
    'natures lore': DeckBucket.ramp,
    "nature's lore": DeckBucket.ramp,
    'three visits': DeckBucket.ramp,
    'farseek': DeckBucket.ramp,
    'cultivate': DeckBucket.ramp,
    'kodamas reach': DeckBucket.ramp,
    "kodama's reach": DeckBucket.ramp,
    'rampant growth': DeckBucket.ramp,
    'skyshroud claim': DeckBucket.ramp,
    'wild growth': DeckBucket.ramp,
    'utopia sprawl': DeckBucket.ramp,
    'birds of paradise': DeckBucket.ramp,
    'llanowar elves': DeckBucket.ramp,
    'elvish mystic': DeckBucket.ramp,
    'fyndhorn elves': DeckBucket.ramp,
    'delighted halfling': DeckBucket.ramp,
    'wood elves': DeckBucket.ramp,
    'sakura-tribe elder': DeckBucket.ramp,
    'sakura-tribe scout': DeckBucket.ramp,
    'smothering tithe': DeckBucket.ramp,
    'dockside extortionist': DeckBucket.ramp,
    'dark ritual': DeckBucket.ramp,
    'cabal ritual': DeckBucket.ramp,
    'jeskas will': DeckBucket.ramp,
    "jeska's will": DeckBucket.ramp,

    // Card Draw & Advantage
    'rhystic study': DeckBucket.draw,
    'mystic remora': DeckBucket.draw,
    'esper sentinel': DeckBucket.draw,
    'the one ring': DeckBucket.draw,
    'skullclamp': DeckBucket.draw,
    'sylvan library': DeckBucket.draw,
    'phyrexian arena': DeckBucket.draw,
    'black market connections': DeckBucket.draw,
    'necropotence': DeckBucket.draw,
    'trouble in pairs': DeckBucket.draw,
    'beast whisperer': DeckBucket.draw,
    'guardian project': DeckBucket.draw,
    'the great henge': DeckBucket.draw,
    'toski, bearer of secrets': DeckBucket.draw,
    'bident of thassa': DeckBucket.draw,
    'coastal piracy': DeckBucket.draw,
    'reconnaissance mission': DeckBucket.draw,
    'fact or fiction': DeckBucket.draw,
    'windfall': DeckBucket.draw,
    'wheel of fortune': DeckBucket.draw,
    'ponder': DeckBucket.draw,
    'preordain': DeckBucket.draw,
    'brainstorm': DeckBucket.draw,
    'faithless looting': DeckBucket.draw,
    'nights whisper': DeckBucket.draw,
    "night's whisper": DeckBucket.draw,
    'sign in blood': DeckBucket.draw,
    'read the bones': DeckBucket.draw,
    'painful truths': DeckBucket.draw,
    'rishkars expertise': DeckBucket.draw,
    "rishkar's expertise": DeckBucket.draw,
    'return of the wildspeaker': DeckBucket.draw,
    'shamanic revelation': DeckBucket.draw,
    'welcoming vampire': DeckBucket.draw,
    'mentor of the meek': DeckBucket.draw,
    'tocasias welcome': DeckBucket.draw,
    "tocasia's welcome": DeckBucket.draw,
    'morbid opportunist': DeckBucket.draw,

    // Spot Removal & Interaction
    'swords to plowshares': DeckBucket.spotRemoval,
    'path to exile': DeckBucket.spotRemoval,
    'beast within': DeckBucket.spotRemoval,
    'generous gift': DeckBucket.spotRemoval,
    'assassins trophy': DeckBucket.spotRemoval,
    "assassin's trophy": DeckBucket.spotRemoval,
    'anguished unmaking': DeckBucket.spotRemoval,
    'void rend': DeckBucket.spotRemoval,
    'chaos warp': DeckBucket.spotRemoval,
    'feed the swarm': DeckBucket.spotRemoval,
    'deadly rollick': DeckBucket.spotRemoval,
    'dismember': DeckBucket.spotRemoval,
    'infernal grasp': DeckBucket.spotRemoval,
    'go for the throat': DeckBucket.spotRemoval,
    'doom blade': DeckBucket.spotRemoval,
    'heros downfall': DeckBucket.spotRemoval,
    "hero's downfall": DeckBucket.spotRemoval,
    'despark': DeckBucket.spotRemoval,
    'stroke of midnight': DeckBucket.spotRemoval,
    'pongify': DeckBucket.spotRemoval,
    'rapid hybridization': DeckBucket.spotRemoval,
    'resculpt': DeckBucket.spotRemoval,
    'reality shift': DeckBucket.spotRemoval,
    'natures claim': DeckBucket.spotRemoval,
    "nature's claim": DeckBucket.spotRemoval,
    'force of vigor': DeckBucket.spotRemoval,
    'abrade': DeckBucket.spotRemoval,
    'wear // tear': DeckBucket.spotRemoval,
    'counterspell': DeckBucket.spotRemoval,
    'arcane denial': DeckBucket.spotRemoval,
    'swan song': DeckBucket.spotRemoval,
    'dovins veto': DeckBucket.spotRemoval,
    "dovin's veto": DeckBucket.spotRemoval,
    'an offer you cant refuse': DeckBucket.spotRemoval,
    "an offer you can't refuse": DeckBucket.spotRemoval,
    'fierce guardianship': DeckBucket.spotRemoval,
    'force of will': DeckBucket.spotRemoval,
    'force of negation': DeckBucket.spotRemoval,
    'pact of negation': DeckBucket.spotRemoval,
    'mana drain': DeckBucket.spotRemoval,
    'negate': DeckBucket.spotRemoval,
    'flusterstorm': DeckBucket.spotRemoval,
    'delay': DeckBucket.spotRemoval,

    // Board Wipe
    'blasphemous act': DeckBucket.boardWipe,
    'toxic deluge': DeckBucket.boardWipe,
    'supreme verdict': DeckBucket.boardWipe,
    'wrath of god': DeckBucket.boardWipe,
    'damnation': DeckBucket.boardWipe,
    'farewell': DeckBucket.boardWipe,
    'cyclonic rift': DeckBucket.boardWipe,
    'vanquish the horde': DeckBucket.boardWipe,
    'cleansing nova': DeckBucket.boardWipe,
    'austere command': DeckBucket.boardWipe,
    'merciless eviction': DeckBucket.boardWipe,
    'time wipe': DeckBucket.boardWipe,
    'chain reaction': DeckBucket.boardWipe,
    'scourge of the fleets': DeckBucket.boardWipe,
    'sunfall': DeckBucket.boardWipe,
    'the meathook massacre': DeckBucket.boardWipe,

    // Protection
    'heroic intervention': DeckBucket.protection,
    'teferis protection': DeckBucket.protection,
    "teferi's protection": DeckBucket.protection,
    'boros charm': DeckBucket.protection,
    'flawless maneuver': DeckBucket.protection,
    'deflecting swat': DeckBucket.protection,
    'clever concealment': DeckBucket.protection,
    'akromas will': DeckBucket.protection,
    "akroma's will": DeckBucket.protection,
    'lightning greaves': DeckBucket.protection,
    'swiftfoot boots': DeckBucket.protection,
    'mithril coat': DeckBucket.protection,
    'whispersilk cloak': DeckBucket.protection,
    'mother of runes': DeckBucket.protection,
    'giver of runes': DeckBucket.protection,
    'tamiyos safekeeping': DeckBucket.protection,
    "tamiyo's safekeeping": DeckBucket.protection,
    'tyvars stand': DeckBucket.protection,
    "tyvar's stand": DeckBucket.protection,
    'veil of summer': DeckBucket.protection,

    // Recursion
    'reanimate': DeckBucket.recursion,
    'animate dead': DeckBucket.recursion,
    'necromancy': DeckBucket.recursion,
    'eternal witness': DeckBucket.recursion,
    'timeless witness': DeckBucket.recursion,
    'sun titan': DeckBucket.recursion,
    'sevinnes reclamation': DeckBucket.recursion,
    "sevinne's reclamation": DeckBucket.recursion,
    'regrowth': DeckBucket.recursion,
    'bala ged recovery': DeckBucket.recursion,
    'karmic guide': DeckBucket.recursion,
    'dread return': DeckBucket.recursion,
    'victimize': DeckBucket.recursion,
    'living death': DeckBucket.recursion,

    // Tutors
    'demonic tutor': DeckBucket.tutors,
    'vampiric tutor': DeckBucket.tutors,
    'imperial seal': DeckBucket.tutors,
    'mystical tutor': DeckBucket.tutors,
    'worldly tutor': DeckBucket.tutors,
    'enlightened tutor': DeckBucket.tutors,
    'gamble': DeckBucket.tutors,
    'green suns zenith': DeckBucket.tutors,
    "green sun's zenith": DeckBucket.tutors,
    'finale of devastation': DeckBucket.tutors,
    'chord of calling': DeckBucket.tutors,
    'eldritch evolution': DeckBucket.tutors,
    'diabolic intent': DeckBucket.tutors,
    'grim tutor': DeckBucket.tutors,
    'fabricate': DeckBucket.tutors,
    'whir of invention': DeckBucket.tutors,

    // Win Conditions
    'craterhoof behemoth': DeckBucket.wincons,
    'moonshaker cavalry': DeckBucket.wincons,
    'triumph of the hordes': DeckBucket.wincons,
    'overwhelming stampede': DeckBucket.wincons,
    'torment of hailfire': DeckBucket.wincons,
    'exsanguinate': DeckBucket.wincons,
    'approach of the second sun': DeckBucket.wincons,
    'thassas oracle': DeckBucket.wincons,
    "thassa's oracle": DeckBucket.wincons,
    'laboratory maniac': DeckBucket.wincons,
    'aetherflux reservoir': DeckBucket.wincons,
    'felidar sovereign': DeckBucket.wincons,
    'revel in riches': DeckBucket.wincons,
    'halo fountain': DeckBucket.wincons,
  };

  static DeckBucket? lookup(String cardName) {
    final clean = cardName.trim().toLowerCase();
    return knownStaples[clean];
  }
}
